{"name": "test_accept_order_with_wrong_order_id_failed", "status": "passed", "start": 1726089014436, "stop": 1726089016182, "uuid": "7457cf8f-05d7-406a-a9e2-e281650b4ad1", "historyId": "1033e5a9fb2e5b998202fb692429a6f4", "testCaseId": "1033e5a9fb2e5b998202fb692429a6f4", "fullName": "tests.test_accept_order_endpoint.TestAcceptOrder#test_accept_order_with_wrong_order_id_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order_endpoint"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "HOME"}, {"name": "thread", "value": "17600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order_endpoint"}]}