{"name": "test_get_order_by_wrong_number_failed", "status": "passed", "start": 1726088887598, "stop": 1726088887849, "uuid": "9cd8e242-4a17-4f0f-ab59-2f470c893410", "historyId": "886a458881cd014dd020daafa1c9f800", "testCaseId": "886a458881cd014dd020daafa1c9f800", "fullName": "tests.test_get_order_by_number_endpoint.TestGetOrderByNumber#test_get_order_by_wrong_number_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_number_endpoint"}, {"name": "subSuite", "value": "TestGetOrderByNumber"}, {"name": "host", "value": "HOME"}, {"name": "thread", "value": "17164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_number_endpoint"}]}